config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true

  VALID_CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: VALID_CATEGORIES }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save!
    redirect_to restaurants_path
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy!
    redirect_to restaurants_path, status: :see_other
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save!
    redirect_to restaurant_path(@restaurant)
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.input :phone_number %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/index.html.erb
  <div class="container">
  <h1>All Restaurants:</h1>
  <br>
  <% @restaurants.each do |restaurant| %>
    <%# <img src="https://picsum.photos/200" alt="restaurant-img"> %>
    <h6><%= link_to restaurant.name, restaurant_path(restaurant), class: "restaurant-list-item" %></h6>
  <% end %>
  <br>
  <%= link_to "Create new Restaurant", new_restaurant_path, class: "btn btn-primary"%>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h2>Create new Restaurant</h2>
  <br >
    <%= render "form", restaurant: @restaurant%>
    <br>
    <br>
    <%= link_to "Go Back", restaurants_path, class: "btn btn-secondary" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>
  <br>
  <p><strong>Category:</strong> <%= @restaurant.category.capitalize %></p>
  <p><strong>Address:</strong> <%= @restaurant.address %></p>
  <p><strong>Phone Number: </strong><%= @restaurant.phone_number %></p>
  <%= link_to "Go Back", restaurants_path, class: "btn btn-primary" %>
  <%= link_to "Delete Restaurant", restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button btn btn-danger" %>
  <br>
  <br>
  <hr>
  <br>
  <h4>Reviews</h4>
  <br>
  <% @restaurant.reviews.each do |review| %>
    <p><strong>Rating: </strong><%= review.rating %>/5</p>
    <p>"<%= review.content %>"</p>
  <%end%>
  <%= link_to "Add review", new_restaurant_review_path(@restaurant), class: "btn btn-secondary" %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [restaurant, review] do |f| %>
  <%= f.input :rating, collection: ["5", "4", "3", "2", "1"] %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/reviews/index.html.erb
  <div class="container">
  <h1>All Reviews:</h1>
  <br>
  <% @reviews.each do |review| %>
    <h6><%= link_to review.content, review_path(review) %></h6>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h2>Add new Review for <u><%= @restaurant.name %></u></h2>
  <br >
  <%= render "form", restaurant: @restaurant, review: @review %>
</div>